name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
 
    - name: Preparation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
 
    - name: Build documentation and update Github Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git reset --hard origin/$GITHUB_REF_NAME
        docs/buildDocs.sh
      shell: bash
